from app.schemas.watchlist import (
    CompanyWatchlistItem,
    ProductWatchlistItem,
    StockWatchlistItem,
    TopicWatchlistItem,
)


def initial_stock_watchlist() -> list[StockWatchlistItem]:
    return [
        StockWatchlistItem(
            ticker="MU",
            company_name="Micron Technology",
            exchange="NASDAQ",
            sector="Technology",
            industry="Semiconductors",
            priority="High",
            group_name="Memory / Storage",
            is_pinned=True,
            related_keywords=[
                "HBM",
                "DRAM",
                "NAND",
                "data center",
                "AI server",
                "memory pricing",
            ],
            related_companies=["NVDA", "AMD", "AVGO", "TSM"],
            related_ai_themes=[
                "HBM memory",
                "AI server memory",
                "data center capex",
            ],
            notes="Monitor AI infrastructure memory demand and pricing cycle signals.",
        ),
        StockWatchlistItem(
            ticker="MRVL",
            company_name="Marvell Technology",
            exchange="NASDAQ",
            sector="Technology",
            industry="Semiconductors",
            priority="High",
            group_name="AI Chips",
            is_pinned=True,
            related_keywords=[
                "custom silicon",
                "ASIC",
                "AI data center",
                "optical interconnect",
                "cloud AI",
            ],
            related_companies=["NVDA", "AMD", "AVGO", "TSM"],
            related_ai_themes=[
                "custom silicon",
                "AI data center networking",
                "optical interconnect",
            ],
            notes="Monitor AI custom silicon and data center connectivity growth.",
        ),
        StockWatchlistItem(
            ticker="SNDK",
            company_name="SanDisk",
            exchange="NASDAQ",
            sector="Technology",
            industry="Computer Hardware",
            priority="Medium",
            group_name="Memory / Storage",
            is_pinned=False,
            related_keywords=[
                "NAND",
                "SSD",
                "storage",
                "enterprise storage",
                "data center",
            ],
            related_companies=["MU", "WDC", "STX"],
            related_ai_themes=[
                "NAND storage",
                "enterprise SSD",
                "AI data storage",
            ],
            notes="Monitor AI storage demand and NAND cycle signals.",
        ),
    ]


def initial_topic_watchlist() -> list[TopicWatchlistItem]:
    return [
        TopicWatchlistItem(
            topic="ai-coding-agents",
            label="AI coding agents",
            category="technical_trend",
            priority="High",
            is_pinned=True,
            related_terms=[
                "coding agent",
                "agentic coding",
                "software engineering agent",
                "code generation",
            ],
            notes="Track coding agents, IDE-native agents, and autonomous software workflows.",
        ),
        TopicWatchlistItem(
            topic="agent-workflows",
            label="Agent workflows",
            category="technical_trend",
            priority="High",
            is_pinned=True,
            related_terms=[
                "agent harness",
                "tool use",
                "multi-agent",
                "MCP",
                "agent memory",
            ],
            notes="Watch for durable patterns in agent orchestration, tools, and memory.",
        ),
        TopicWatchlistItem(
            topic="open-source-llms",
            label="Open-source LLMs",
            category="research",
            priority="High",
            is_pinned=True,
            related_terms=[
                "open weights",
                "model release",
                "inference",
                "fine-tuning",
            ],
            notes="Monitor model releases, benchmark movement, and deployment cost shifts.",
        ),
        TopicWatchlistItem(
            topic="ai-infrastructure",
            label="AI infrastructure",
            category="technical_trend",
            priority="High",
            related_terms=[
                "GPU",
                "ASIC",
                "inference optimization",
                "data center",
                "serving",
            ],
            notes="Connect technical infra news with stock-watchlist context.",
        ),
        TopicWatchlistItem(
            topic="multimodal-models",
            label="Multimodal models",
            category="research",
            priority="Medium",
            related_terms=[
                "vision language model",
                "audio model",
                "video generation",
                "multimodal reasoning",
            ],
            notes="Track model capability shifts across image, audio, video, and reasoning.",
        ),
        TopicWatchlistItem(
            topic="ai-products",
            label="AI products",
            category="product",
            priority="Medium",
            related_terms=[
                "AI app",
                "AI search",
                "AI browser",
                "AI productivity",
                "launch",
            ],
            notes="Catch new user-facing products and AI-native workflows.",
        ),
    ]


def initial_company_watchlist() -> list[CompanyWatchlistItem]:
    return [
        CompanyWatchlistItem(
            company_key="nvidia",
            company_name="NVIDIA",
            ticker="NVDA",
            category="semiconductor",
            priority="High",
            is_pinned=True,
            related_terms=["GPU", "CUDA", "AI accelerator", "data center"],
            notes="Track GPU demand, platform shifts, and AI infrastructure signals.",
        ),
        CompanyWatchlistItem(
            company_key="amd",
            company_name="AMD",
            ticker="AMD",
            category="semiconductor",
            priority="High",
            related_terms=["GPU", "MI300", "AI accelerator", "data center"],
            notes="Monitor AI accelerator competition and data center adoption.",
        ),
        CompanyWatchlistItem(
            company_key="broadcom",
            company_name="Broadcom",
            ticker="AVGO",
            category="semiconductor",
            priority="High",
            related_terms=["custom silicon", "ASIC", "networking", "AI data center"],
            notes="Watch custom AI silicon and networking demand.",
        ),
        CompanyWatchlistItem(
            company_key="tsmc",
            company_name="TSMC",
            ticker="TSM",
            category="semiconductor",
            priority="High",
            related_terms=["foundry", "CoWoS", "advanced packaging", "AI chips"],
            notes="Track manufacturing capacity signals for AI accelerators.",
        ),
        CompanyWatchlistItem(
            company_key="asml",
            company_name="ASML",
            ticker="ASML",
            category="semiconductor",
            priority="Medium",
            related_terms=["EUV", "lithography", "semiconductor equipment"],
            notes="Monitor upstream semiconductor equipment constraints.",
        ),
        CompanyWatchlistItem(
            company_key="microsoft",
            company_name="Microsoft",
            ticker="MSFT",
            category="cloud_ai",
            priority="Medium",
            related_terms=["Azure AI", "Copilot", "OpenAI", "cloud capex"],
            notes="Track cloud AI demand, Copilot adoption, and OpenAI linkage.",
        ),
        CompanyWatchlistItem(
            company_key="amazon",
            company_name="Amazon",
            ticker="AMZN",
            category="cloud_ai",
            priority="Medium",
            related_terms=["AWS", "Trainium", "Bedrock", "cloud capex"],
            notes="Watch AWS AI infrastructure and product adoption.",
        ),
        CompanyWatchlistItem(
            company_key="meta",
            company_name="Meta",
            ticker="META",
            category="ai_platform",
            priority="Medium",
            related_terms=["Llama", "AI assistant", "AI capex", "open model"],
            notes="Monitor open-model releases and AI infrastructure spend.",
        ),
        CompanyWatchlistItem(
            company_key="openai",
            company_name="OpenAI",
            category="ai_lab",
            priority="High",
            is_pinned=True,
            related_terms=["ChatGPT", "Sora", "agent", "model release"],
            notes="Track frontier model, product, and partnership signals.",
        ),
        CompanyWatchlistItem(
            company_key="anthropic",
            company_name="Anthropic",
            category="ai_lab",
            priority="High",
            related_terms=["Claude", "agent", "AI safety", "model release"],
            notes="Track Claude releases, enterprise adoption, and safety research.",
        ),
    ]


def initial_product_watchlist() -> list[ProductWatchlistItem]:
    return [
        ProductWatchlistItem(
            category="ai-coding-tools",
            label="AI coding tools",
            priority="High",
            is_pinned=True,
            related_terms=[
                "coding assistant",
                "developer agent",
                "IDE agent",
                "code review",
            ],
            notes="Track AI-native software development tools and coding-agent workflows.",
        ),
        ProductWatchlistItem(
            category="ai-search-browsers",
            label="AI search and browsers",
            priority="Medium",
            related_terms=[
                "AI search",
                "browser agent",
                "answer engine",
                "research assistant",
            ],
            notes="Watch search, browsing, and research products with agentic workflows.",
        ),
        ProductWatchlistItem(
            category="ai-productivity",
            label="AI productivity",
            priority="Medium",
            related_terms=[
                "meeting notes",
                "workflow automation",
                "document assistant",
                "knowledge management",
            ],
            notes="Follow user-facing productivity products and workflow automation launches.",
        ),
    ]
