from app.schemas.watchlist import StockWatchlistItem, TopicWatchlistItem


def initial_stock_watchlist() -> list[StockWatchlistItem]:
    return [
        StockWatchlistItem(
            ticker="MU",
            company_name="Micron Technology",
            exchange="NASDAQ",
            sector="Technology",
            industry="Semiconductors",
            priority="High",
            group_name="Memory / Storage",
            is_pinned=True,
            related_keywords=[
                "HBM",
                "DRAM",
                "NAND",
                "data center",
                "AI server",
                "memory pricing",
            ],
            related_companies=["NVDA", "AMD", "AVGO", "TSM"],
            related_ai_themes=[
                "HBM memory",
                "AI server memory",
                "data center capex",
            ],
            notes="Monitor AI infrastructure memory demand and pricing cycle signals.",
        ),
        StockWatchlistItem(
            ticker="MRVL",
            company_name="Marvell Technology",
            exchange="NASDAQ",
            sector="Technology",
            industry="Semiconductors",
            priority="High",
            group_name="AI Chips",
            is_pinned=True,
            related_keywords=[
                "custom silicon",
                "ASIC",
                "AI data center",
                "optical interconnect",
                "cloud AI",
            ],
            related_companies=["NVDA", "AMD", "AVGO", "TSM"],
            related_ai_themes=[
                "custom silicon",
                "AI data center networking",
                "optical interconnect",
            ],
            notes="Monitor AI custom silicon and data center connectivity growth.",
        ),
        StockWatchlistItem(
            ticker="SNDK",
            company_name="SanDisk",
            exchange="NASDAQ",
            sector="Technology",
            industry="Computer Hardware",
            priority="Medium",
            group_name="Memory / Storage",
            is_pinned=False,
            related_keywords=[
                "NAND",
                "SSD",
                "storage",
                "enterprise storage",
                "data center",
            ],
            related_companies=["MU", "WDC", "STX"],
            related_ai_themes=[
                "NAND storage",
                "enterprise SSD",
                "AI data storage",
            ],
            notes="Monitor AI storage demand and NAND cycle signals.",
        ),
    ]


def initial_topic_watchlist() -> list[TopicWatchlistItem]:
    return [
        TopicWatchlistItem(
            topic="ai-coding-agents",
            label="AI coding agents",
            category="technical_trend",
            priority="High",
            is_pinned=True,
            related_terms=[
                "coding agent",
                "agentic coding",
                "software engineering agent",
                "code generation",
            ],
            notes="Track coding agents, IDE-native agents, and autonomous software workflows.",
        ),
        TopicWatchlistItem(
            topic="agent-workflows",
            label="Agent workflows",
            category="technical_trend",
            priority="High",
            is_pinned=True,
            related_terms=[
                "agent harness",
                "tool use",
                "multi-agent",
                "MCP",
                "agent memory",
            ],
            notes="Watch for durable patterns in agent orchestration, tools, and memory.",
        ),
        TopicWatchlistItem(
            topic="open-source-llms",
            label="Open-source LLMs",
            category="research",
            priority="High",
            is_pinned=True,
            related_terms=[
                "open weights",
                "model release",
                "inference",
                "fine-tuning",
            ],
            notes="Monitor model releases, benchmark movement, and deployment cost shifts.",
        ),
        TopicWatchlistItem(
            topic="ai-infrastructure",
            label="AI infrastructure",
            category="technical_trend",
            priority="High",
            related_terms=[
                "GPU",
                "ASIC",
                "inference optimization",
                "data center",
                "serving",
            ],
            notes="Connect technical infra news with stock-watchlist context.",
        ),
        TopicWatchlistItem(
            topic="multimodal-models",
            label="Multimodal models",
            category="research",
            priority="Medium",
            related_terms=[
                "vision language model",
                "audio model",
                "video generation",
                "multimodal reasoning",
            ],
            notes="Track model capability shifts across image, audio, video, and reasoning.",
        ),
        TopicWatchlistItem(
            topic="ai-products",
            label="AI products",
            category="product",
            priority="Medium",
            related_terms=[
                "AI app",
                "AI search",
                "AI browser",
                "AI productivity",
                "launch",
            ],
            notes="Catch new user-facing products and AI-native workflows.",
        ),
    ]
